SET IDENTITY_INSERT CITY ON
insert into CITY (City_Id, City_Name, CState) values (3, 'Chicago', 'Illinois');
insert into CITY (City_Id, City_Name, CState) values (4, 'Washington', 'District of Columbia');
insert into CITY (City_Id, City_Name, CState) values (5, 'Washington', 'District of Columbia');
insert into CITY (City_Id, City_Name, CState) values (6, 'Oklahoma City', 'Oklahoma');
insert into CITY (City_Id, City_Name, CState) values (7, 'Columbus', 'Ohio');
insert into CITY (City_Id, City_Name, CState) values (8, 'San Jose', 'California');
insert into CITY (City_Id, City_Name, CState) values (9, 'Miami', 'Florida');
insert into CITY (City_Id, City_Name, CState) values (10, 'Boston', 'Massachusetts');
insert into CITY (City_Id, City_Name, CState) values (11, 'Charleston', 'West Virginia');
insert into CITY (City_Id, City_Name, CState) values (12, 'Toledo', 'Ohio');
insert into CITY (City_Id, City_Name, CState) values (13, 'Saint Louis', 'Missouri');
insert into CITY (City_Id, City_Name, CState) values (14, 'Salt Lake City', 'Utah');
insert into CITY (City_Id, City_Name, CState) values (15, 'Tampa', 'Florida');
insert into CITY (City_Id, City_Name, CState) values (16, 'Atlanta', 'Georgia');
insert into CITY (City_Id, City_Name, CState) values (17, 'Houston', 'Texas');
insert into CITY (City_Id, City_Name, CState) values (18, 'Chicago', 'Illinois');
insert into CITY (City_Id, City_Name, CState) values (19, 'Bronx', 'New York');
insert into CITY (City_Id, City_Name, CState) values (20, 'Washington', 'District of Columbia');
insert into CITY (City_Id, City_Name, CState) values (21, 'San Diego', 'California');
insert into CITY (City_Id, City_Name, CState) values (22, 'Houston', 'Texas');
insert into CITY (City_Id, City_Name, CState) values (23, 'Saint Louis', 'Missouri');
insert into CITY (City_Id, City_Name, CState) values (24, 'Paterson', 'New Jersey');
insert into CITY (City_Id, City_Name, CState) values (25, 'New York City', 'New York');
insert into CITY (City_Id, City_Name, CState) values (26, 'Baltimore', 'Maryland');
insert into CITY (City_Id, City_Name, CState) values (27, 'Huntington Beach', 'California');
insert into CITY (City_Id, City_Name, CState) values (28, 'Sioux City', 'Iowa');
insert into CITY (City_Id, City_Name, CState) values (29, 'Fullerton', 'California');
insert into CITY (City_Id, City_Name, CState) values (30, 'Jefferson City', 'Missouri');
insert into CITY (City_Id, City_Name, CState) values (31, 'Irvine', 'California');
insert into CITY (City_Id, City_Name, CState) values (32, 'Saint Paul', 'Minnesota');
insert into CITY (City_Id, City_Name, CState) values (33, 'Daytona Beach', 'Florida');
insert into CITY (City_Id, City_Name, CState) values (34, 'Phoenix', 'Arizona');
insert into CITY (City_Id, City_Name, CState) values (35, 'Katy', 'Texas');
insert into CITY (City_Id, City_Name, CState) values (36, 'Houston', 'Texas');
insert into CITY (City_Id, City_Name, CState) values (37, 'Columbus', 'Ohio');
insert into CITY (City_Id, City_Name, CState) values (38, 'Atlanta', 'Georgia');
insert into CITY (City_Id, City_Name, CState) values (39, 'Phoenix', 'Arizona');
insert into CITY (City_Id, City_Name, CState) values (40, 'Greensboro', 'North Carolina');
insert into CITY (City_Id, City_Name, CState) values (41, 'Nashville', 'Tennessee');
insert into CITY (City_Id, City_Name, CState) values (42, 'Omaha', 'Nebraska');
insert into CITY (City_Id, City_Name, CState) values (43, 'Lakeland', 'Florida');
insert into CITY (City_Id, City_Name, CState) values (44, 'Terre Haute', 'Indiana');
insert into CITY (City_Id, City_Name, CState) values (45, 'Denver', 'Colorado');
insert into CITY (City_Id, City_Name, CState) values (46, 'North Little Rock', 'Arkansas');
insert into CITY (City_Id, City_Name, CState) values (47, 'Young America', 'Minnesota');
insert into CITY (City_Id, City_Name, CState) values (48, 'Lincoln', 'Nebraska');
insert into CITY (City_Id, City_Name, CState) values (49, 'Harrisburg', 'Pennsylvania');
insert into CITY (City_Id, City_Name, CState) values (50, 'Arlington', 'Texas');
insert into CITY (City_Id, City_Name, CState) values (51, 'Roanoke', 'Virginia');
insert into CITY (City_Id, City_Name, CState) values (52, 'Macon', 'Georgia');
insert into CITY (City_Id, City_Name, CState) values (53, 'Oklahoma City', 'Oklahoma');
insert into CITY (City_Id, City_Name, CState) values (54, 'Oakland', 'California');
insert into CITY (City_Id, City_Name, CState) values (55, 'New York City', 'New York');
insert into CITY (City_Id, City_Name, CState) values (56, 'Saint Louis', 'Missouri');
insert into CITY (City_Id, City_Name, CState) values (57, 'Saint Paul', 'Minnesota');
insert into CITY (City_Id, City_Name, CState) values (58, 'Knoxville', 'Tennessee');
insert into CITY (City_Id, City_Name, CState) values (59, 'Huntington', 'West Virginia');
insert into CITY (City_Id, City_Name, CState) values (60, 'El Paso', 'Texas');
insert into CITY (City_Id, City_Name, CState) values (61, 'New Orleans', 'Louisiana');
insert into CITY (City_Id, City_Name, CState) values (62, 'Santa Cruz', 'California');
insert into CITY (City_Id, City_Name, CState) values (63, 'Dayton', 'Ohio');
insert into CITY (City_Id, City_Name, CState) values (64, 'Philadelphia', 'Pennsylvania');
insert into CITY (City_Id, City_Name, CState) values (65, 'Irvine', 'California');
insert into CITY (City_Id, City_Name, CState) values (66, 'Austin', 'Texas');
insert into CITY (City_Id, City_Name, CState) values (67, 'Lake Worth', 'Florida');
insert into CITY (City_Id, City_Name, CState) values (68, 'Anaheim', 'California');
insert into CITY (City_Id, City_Name, CState) values (69, 'Lexington', 'Kentucky');
insert into CITY (City_Id, City_Name, CState) values (70, 'Washington', 'District of Columbia');
insert into CITY (City_Id, City_Name, CState) values (71, 'Atlanta', 'Georgia');
insert into CITY (City_Id, City_Name, CState) values (72, 'Vancouver', 'Washington');
insert into CITY (City_Id, City_Name, CState) values (73, 'Rochester', 'New York');
insert into CITY (City_Id, City_Name, CState) values (74, 'Vero Beach', 'Florida');
insert into CITY (City_Id, City_Name, CState) values (75, 'Norfolk', 'Virginia');
insert into CITY (City_Id, City_Name, CState) values (76, 'Colorado Springs', 'Colorado');
insert into CITY (City_Id, City_Name, CState) values (77, 'Hartford', 'Connecticut');
insert into CITY (City_Id, City_Name, CState) values (78, 'Des Moines', 'Iowa');
insert into CITY (City_Id, City_Name, CState) values (79, 'Washington', 'District of Columbia');
insert into CITY (City_Id, City_Name, CState) values (80, 'Roanoke', 'Virginia');
insert into CITY (City_Id, City_Name, CState) values (81, 'South Bend', 'Indiana');
insert into CITY (City_Id, City_Name, CState) values (82, 'Washington', 'District of Columbia');
insert into CITY (City_Id, City_Name, CState) values (83, 'Harrisburg', 'Pennsylvania');
insert into CITY (City_Id, City_Name, CState) values (84, 'San Diego', 'California');
insert into CITY (City_Id, City_Name, CState) values (85, 'Tulsa', 'Oklahoma');
insert into CITY (City_Id, City_Name, CState) values (86, 'Hartford', 'Connecticut');
insert into CITY (City_Id, City_Name, CState) values (87, 'Houston', 'Texas');
insert into CITY (City_Id, City_Name, CState) values (88, 'Saint Louis', 'Missouri');
insert into CITY (City_Id, City_Name, CState) values (89, 'Seattle', 'Washington');
insert into CITY (City_Id, City_Name, CState) values (90, 'Birmingham', 'Alabama');
insert into CITY (City_Id, City_Name, CState) values (91, 'San Antonio', 'Texas');
insert into CITY (City_Id, City_Name, CState) values (92, 'Torrance', 'California');
insert into CITY (City_Id, City_Name, CState) values (93, 'Winter Haven', 'Florida');
insert into CITY (City_Id, City_Name, CState) values (94, 'Philadelphia', 'Pennsylvania');
insert into CITY (City_Id, City_Name, CState) values (95, 'Boston', 'Massachusetts');
insert into CITY (City_Id, City_Name, CState) values (96, 'Garden Grove', 'California');
insert into CITY (City_Id, City_Name, CState) values (97, 'Austin', 'Texas');
insert into CITY (City_Id, City_Name, CState) values (98, 'San Diego', 'California');
insert into CITY (City_Id, City_Name, CState) values (99, 'Detroit', 'Michigan');
insert into CITY (City_Id, City_Name, CState) values (100, 'Dallas', 'Texas');
insert into CITY (City_Id, City_Name, CState) values (101, 'Fresno', 'California');
insert into CITY (City_Id, City_Name, CState) values (102, 'Tallahassee', 'Florida');
insert into CITY (City_Id, City_Name, CState) values (103, 'Dallas', 'Texas');
insert into CITY (City_Id, City_Name, CState) values (104, 'Las Vegas', 'Nevada');
insert into CITY (City_Id, City_Name, CState) values (105, 'Alexandria', 'Virginia');
insert into CITY (City_Id, City_Name, CState) values (106, 'Atlanta', 'Georgia');
insert into CITY (City_Id, City_Name, CState) values (107, 'Denver', 'Colorado');
insert into CITY (City_Id, City_Name, CState) values (108, 'Fresno', 'California');
insert into CITY (City_Id, City_Name, CState) values (109, 'Macon', 'Georgia');
insert into CITY (City_Id, City_Name, CState) values (110, 'Oklahoma City', 'Oklahoma');
insert into CITY (City_Id, City_Name, CState) values (111, 'Laurel', 'Maryland');
insert into CITY (City_Id, City_Name, CState) values (112, 'Corpus Christi', 'Texas');
insert into CITY (City_Id, City_Name, CState) values (113, 'Boston', 'Massachusetts');
insert into CITY (City_Id, City_Name, CState) values (114, 'Norcross', 'Georgia');
insert into CITY (City_Id, City_Name, CState) values (115, 'Peoria', 'Illinois');
insert into CITY (City_Id, City_Name, CState) values (116, 'San Diego', 'California');
insert into CITY (City_Id, City_Name, CState) values (117, 'Montgomery', 'Alabama');
insert into CITY (City_Id, City_Name, CState) values (118, 'Anniston', 'Alabama');
insert into CITY (City_Id, City_Name, CState) values (119, 'Seattle', 'Washington');
insert into CITY (City_Id, City_Name, CState) values (120, 'Houston', 'Texas');
insert into CITY (City_Id, City_Name, CState) values (121, 'Saginaw', 'Michigan');
insert into CITY (City_Id, City_Name, CState) values (122, 'Mobile', 'Alabama');
insert into CITY (City_Id, City_Name, CState) values (123, 'Duluth', 'Minnesota');
insert into CITY (City_Id, City_Name, CState) values (124, 'Brockton', 'Massachusetts');
insert into CITY (City_Id, City_Name, CState) values (125, 'Dallas', 'Texas');
