insert into COACH (coach_Name, t_Name, c_champWins) values ('Zecchi', 'Tolmie''s Owl''s-clover', 62);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Hanscombe', 'Dotted Wild Coffee', 67);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Dannel', 'Slender False Garlic', 50);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Crookshanks', 'Tarweed', 1);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Schwant', 'Longleaf Primrose-willow', 32);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Strass', 'Showy Phlox', 13);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Ciccoloi', 'Island Senecio', 68);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Rauprich', 'Yellow Meadowbeauty', 99);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Crotty', 'Mexican Bladdersage', 91);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Bewlie', 'Virginia Quillwort', 34);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Gives', 'Arborescent Pricklypear', 44);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Ellum', 'Spilanthes', 63);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Seaward', 'Brickellbush', 43);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Ketcher', 'Lanszwert''s Pea', 74);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Marian', 'Plantain Goldenweed', 17);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Brightman', 'Snow Mountain Beardtongue', 89);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Heningam', 'Old Man''s Whiskers', 36);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Vernazza', 'Bachang', 9);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Burnhill', 'Torrey''s Tievine', 94);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Colenutt', 'Quebracho', 62);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Alderman', 'Unequal Leaf Bryoerythrophyllum Moss', 54);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Fontell', 'Whitemargin Phlox', 29);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Minghella', 'Chaenothecopsis Lichen', 4);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Rasher', 'Beach Suncup', 12);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Maylin', 'Smallflower Columbine', 100);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Shury', 'Atlantic Goldenrod', 34);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Caris', 'Carolina Leaf-flower', 7);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Puller', 'Pohlia Moss', 100);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Blind', 'Field Pennycress', 56);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Grossier', 'Byssoloma Lichen', 53);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Deacock', 'Sanddune Wallflower', 57);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Le Fleming', 'Prickly Russian Thistle', 67);
insert into COACH (coach_Name, t_Name, c_champWins) values ('McAlister', 'Spiral Ginger', 53);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Scalera', 'Spiked Ipomopsis', 44);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Burnside', 'Koehler''s Rockcress', 37);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Kemet', 'Pale Bastard Toadflax', 52);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Andreia', 'Weak Spurge', 27);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Lough', 'Gentian', 78);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Heinemann', 'Canadian Licorice-root', 58);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Adshead', 'Dooryard Dock', 90);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Coram', 'Zygodon Moss', 99);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Tosspell', 'Catillaria Lichen', 72);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Daniello', 'Fivefingers', 49);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Klaesson', 'Cusick''s Popcornflower', 39);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Poli', 'Davis Mountain Oak', 65);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Armatidge', 'Sessileleaf Bellwort', 12);
insert into COACH (coach_Name, t_Name, c_champWins) values ('d'' Eye', 'Evans'' Felt Lichen', 59);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Guiot', 'Albizia', 3);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Boays', 'Earth Lichen', 80);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Opie', 'Chinese Fir', 71);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Soldner', 'Adobe Lily', 88);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Lounds', 'Broom Crowberry', 36);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Dunning', 'Bulblet-bearing Water Hemlock', 30);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Dight', 'Gray''s Flatsedge', 74);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Doughton', 'Hoary Ticktrefoil', 69);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Advani', 'Brant''s Oak', 57);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Aleksandrov', 'Selkirk''s Violet', 28);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Reicherz', 'Pine Violet', 7);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Bantock', 'Rim Lichen', 16);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Worrell', 'Orthotrichum Moss', 68);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Cunnow', 'Gymnadenia', 90);
insert into COACH (coach_Name, t_Name, c_champWins) values ('O'' Byrne', 'Dense Blazing Star', 42);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Risson', 'Plum Pine', 26);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Tarpey', 'San Joaquin Dodder', 59);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Sygrove', 'Forked Fanwort', 42);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Stockell', 'California Brome', 10);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Tyrer', 'Dicranum Moss', 40);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Liversidge', 'Rayless Sunflower', 10);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Zapatero', 'Matted Lichen', 36);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Sneden', 'Queen''s-delight', 59);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Seemmonds', 'Subterranean Indian Breadroot', 83);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Adam', 'Godfrey''s Thoroughwort', 56);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Osburn', 'Ragged Lichen', 60);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Biddy', 'Branching Phacelia', 31);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Creane', 'Hopue', 25);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Gowling', 'Long-leaf Beak Sedge', 61);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Beves', 'Parry''s Thistle', 64);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Beranek', 'Darlington''s Glade Spurge', 47);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Andreacci', 'White Sage', 89);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Bullus', 'Dicranum Moss', 38);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Shoobridge', 'Oneawn Spineflower', 83);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Conyard', 'White Sagebrush', 55);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Maffi', 'Cypress Spurge', 3);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Quantrill', 'Rush Pussytoes', 4);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Huyche', 'Vahl''s Cinquefoil', 71);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Dawby', 'Ropalospora Lichen', 3);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Lorden', 'Green Fiddleneck', 76);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Bourner', 'Parks'' Stoneseed', 34);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Docwra', 'Golden Dwarfgentian', 3);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Durden', 'Sea Fig', 47);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Stobbe', 'Marsh Bellflower', 51);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Prescot', 'Caribbean Bristlegrass', 15);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Cordier', 'Pseudolmedia', 98);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Eminson', 'Devilshead', 84);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Fulloway', 'Starveling Milkvetch', 52);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Alyoshin', 'Narrowleaf Blue-eyed Grass', 53);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Poacher', 'Siberian Crab Apple', 12);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Cyson', 'Wild Coco', 87);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Trainor', 'Kaumahana', 82);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Richter', 'Coville''s Serviceberry', 75);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Tuttle', 'Cymbalaria', 30);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Beatey', 'Cleft Phlox', 21);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Warboys', 'Holboell''s Rockcress', 70);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Aldgate', 'Blackish Locoweed', 97);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Iddons', 'West Indian Bluestem', 56);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Beange', 'Hill''s Lupine', 19);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Christian', 'Teosinte', 77);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Giottoi', 'Andreaea Moss', 41);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Sudlow', 'Japanese Jasmine', 74);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Rubartelli', 'Speargrass', 16);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Bufton', 'Bryum Moss', 45);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Sawford', 'Fall Tansyaster', 37);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Mathen', 'Western Inflated Sedge', 18);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Putland', 'Kangaroo Grass', 52);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Moreing', 'Beaked Hawksbeard', 86);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Wybron', 'Pohaku Cyanea', 51);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Tyce', 'Rocoto', 56);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Dobbison', 'Tiburon Indian Paintbrush', 62);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Crawford', 'Netted Shrubverbena', 74);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Stouther', 'Zeller''s Mock Orange', 74);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Stigell', 'Dwarf Phlox', 92);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Rigney', 'Schied''s Snakeherb', 76);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Vagges', 'Sulphur Lichen', 45);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Polly', 'Yellow Carolina Milkvine', 61);
insert into COACH (coach_Name, t_Name, c_champWins) values ('Krysztofiak', 'Pilot Range Cinquefoil', 85);
