insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (1, 'Ingunna', 984070, 'Tolmie''s Owl''s-clover');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (2, 'Hillary', 832815, 'Dotted Wild Coffee');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (3, 'Kittie', 381578, 'Slender False Garlic');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (4, 'Cos', 298887, 'Tarweed');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (5, 'Shane', 918327, 'Longleaf Primrose-willow');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (6, 'Babb', 881993, 'Showy Phlox');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (7, 'Ragnar', 470688, 'Island Senecio');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (8, 'Othello', 153317, 'Yellow Meadowbeauty');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (9, 'Maiga', 339510, 'Mexican Bladdersage');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (10, 'Adella', 119417, 'Virginia Quillwort');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (11, 'Claudetta', 371665, 'Arborescent Pricklypear');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (12, 'Verina', 886551, 'Spilanthes');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (13, 'Amata', 589545, 'Brickellbush');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (14, 'Anderea', 197851, 'Lanszwert''s Pea');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (15, 'Alexis', 546247, 'Plantain Goldenweed');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (16, 'Bonnee', 800188, 'Snow Mountain Beardtongue');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (17, 'Gussi', 343803, 'Old Man''s Whiskers');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (18, 'Irita', 522491, 'Bachang');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (19, 'Adrien', 563470, 'Torrey''s Tievine');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (20, 'Cara', 576127, 'Quebracho');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (21, 'Georas', 603061, 'Unequal Leaf Bryoerythrophyllum Moss');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (22, 'Florian', 648263, 'Whitemargin Phlox');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (23, 'Ezequiel', 261035, 'Chaenothecopsis Lichen');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (24, 'Hardy', 533110, 'Beach Suncup');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (25, 'Fredericka', 866495, 'Smallflower Columbine');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (26, 'Bette', 239136, 'Atlantic Goldenrod');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (27, 'Winston', 409945, 'Carolina Leaf-flower');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (28, 'Rebekah', 230374, 'Pohlia Moss');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (29, 'Tyrone', 832545, 'Field Pennycress');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (30, 'Norrie', 932301, 'Byssoloma Lichen');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (31, 'Christie', 254454, 'Sanddune Wallflower');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (32, 'Robbi', 386162, 'Prickly Russian Thistle');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (33, 'Allyce', 535395, 'Spiral Ginger');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (34, 'Alvis', 773982, 'Spiked Ipomopsis');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (35, 'Titus', 665936, 'Koehler''s Rockcress');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (36, 'Cathe', 148351, 'Pale Bastard Toadflax');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (37, 'Susana', 806012, 'Weak Spurge');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (38, 'Merna', 78762, 'Gentian');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (39, 'Nance', 842330, 'Canadian Licorice-root');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (40, 'Beatrix', 464826, 'Dooryard Dock');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (41, 'Debi', 137892, 'Zygodon Moss');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (42, 'Annalise', 179274, 'Catillaria Lichen');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (43, 'Romeo', 304466, 'Fivefingers');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (44, 'Farrah', 22359, 'Cusick''s Popcornflower');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (45, 'Sterne', 417761, 'Davis Mountain Oak');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (46, 'Kirsti', 10329, 'Sessileleaf Bellwort');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (47, 'Wat', 28500, 'Evans'' Felt Lichen');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (48, 'Thoma', 480382, 'Albizia');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (49, 'Valaree', 885856, 'Earth Lichen');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (50, 'Rodi', 600940, 'Chinese Fir');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (51, 'Micheil', 947744, 'Adobe Lily');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (52, 'Mitzi', 16787, 'Broom Crowberry');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (53, 'Randell', 722823, 'Bulblet-bearing Water Hemlock');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (54, 'Robin', 765566, 'Gray''s Flatsedge');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (55, 'Klaus', 344143, 'Hoary Ticktrefoil');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (56, 'Ursala', 584072, 'Brant''s Oak');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (57, 'Garland', 753476, 'Selkirk''s Violet');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (58, 'Emmaline', 22928, 'Pine Violet');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (59, 'Kippar', 233788, 'Rim Lichen');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (60, 'Misti', 64124, 'Orthotrichum Moss');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (61, 'Pippy', 482910, 'Gymnadenia');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (62, 'Nicolette', 83099, 'Dense Blazing Star');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (63, 'Hadrian', 968995, 'Plum Pine');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (64, 'Theobald', 104153, 'San Joaquin Dodder');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (65, 'Maximilien', 678648, 'Forked Fanwort');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (66, 'Dix', 229810, 'California Brome');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (67, 'Morganne', 221118, 'Dicranum Moss');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (68, 'Jessalyn', 920461, 'Rayless Sunflower');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (69, 'Robinia', 171504, 'Matted Lichen');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (70, 'Sebastien', 664556, 'Queen''s-delight');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (71, 'Baily', 762185, 'Subterranean Indian Breadroot');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (72, 'Marj', 352798, 'Godfrey''s Thoroughwort');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (73, 'Torr', 116736, 'Ragged Lichen');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (74, 'Allister', 365026, 'Branching Phacelia');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (75, 'Archy', 193539, 'Hopue');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (76, 'Belvia', 455629, 'Long-leaf Beak Sedge');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (77, 'Marlin', 214959, 'Parry''s Thistle');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (78, 'Martita', 287544, 'Darlington''s Glade Spurge');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (79, 'Tiffani', 383255, 'White Sage');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (80, 'Eb', 349959, 'Dicranum Moss');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (81, 'Urbain', 15072, 'Oneawn Spineflower');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (82, 'Kata', 408297, 'White Sagebrush');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (83, 'Cori', 88384, 'Cypress Spurge');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (84, 'Kally', 64360, 'Rush Pussytoes');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (85, 'Austine', 811247, 'Vahl''s Cinquefoil');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (86, 'Roselia', 456004, 'Ropalospora Lichen');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (87, 'Fleur', 657187, 'Green Fiddleneck');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (88, 'Miles', 663394, 'Parks'' Stoneseed');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (89, 'Evie', 398244, 'Golden Dwarfgentian');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (90, 'Lara', 180010, 'Sea Fig');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (91, 'Joli', 421813, 'Marsh Bellflower');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (92, 'Samara', 254626, 'Caribbean Bristlegrass');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (93, 'Mickie', 30515, 'Pseudolmedia');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (94, 'Kath', 582275, 'Devilshead');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (95, 'Manfred', 94687, 'Starveling Milkvetch');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (96, 'Shaughn', 85673, 'Narrowleaf Blue-eyed Grass');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (97, 'Gregorio', 292243, 'Siberian Crab Apple');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (98, 'Tabina', 376199, 'Wild Coco');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (99, 'Arnoldo', 458438, 'Kaumahana');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (100, 'Olly', 329494, 'Coville''s Serviceberry');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (101, 'Hagan', 825958, 'Cymbalaria');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (102, 'Juanita', 865633, 'Cleft Phlox');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (103, 'Andeee', 236597, 'Holboell''s Rockcress');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (104, 'Othilie', 776553, 'Blackish Locoweed');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (105, 'Fredi', 533716, 'West Indian Bluestem');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (106, 'Wendell', 523386, 'Hill''s Lupine');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (107, 'Claude', 998498, 'Teosinte');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (108, 'Reynolds', 398892, 'Andreaea Moss');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (109, 'Aurlie', 809665, 'Japanese Jasmine');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (110, 'Raeann', 839866, 'Speargrass');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (111, 'Heywood', 574046, 'Bryum Moss');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (112, 'Bev', 714623, 'Fall Tansyaster');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (113, 'Elnar', 311650, 'Western Inflated Sedge');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (114, 'Anselma', 97959, 'Kangaroo Grass');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (115, 'Lottie', 663257, 'Beaked Hawksbeard');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (116, 'Devy', 998012, 'Pohaku Cyanea');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (117, 'Heddi', 101535, 'Rocoto');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (118, 'Barbie', 787274, 'Tiburon Indian Paintbrush');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (119, 'Brita', 813891, 'Netted Shrubverbena');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (120, 'Ignatius', 306469, 'Zeller''s Mock Orange');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (121, 'Jojo', 312462, 'Dwarf Phlox');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (122, 'Sebastian', 668323, 'Schied''s Snakeherb');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (123, 'Orsola', 441503, 'Sulphur Lichen');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (124, 'Renata', 54464, 'Yellow Carolina Milkvine');
insert into TEAM_OWNER (id_Number, owner_Name, t_Purch_Value, tm_Name) values (125, 'Gwen', 59905, 'Pilot Range Cinquefoil');
