insert into TEAM_WORTH (t_Name, t_Value) values ('Tolmie''s Owl''s-clover', 340109);
insert into TEAM_WORTH (t_Name, t_Value) values ('Dotted Wild Coffee', 542739);
insert into TEAM_WORTH (t_Name, t_Value) values ('Slender False Garlic', 149921);
insert into TEAM_WORTH (t_Name, t_Value) values ('Tarweed', 845151);
insert into TEAM_WORTH (t_Name, t_Value) values ('Longleaf Primrose-willow', 286817);
insert into TEAM_WORTH (t_Name, t_Value) values ('Showy Phlox', 944918);
insert into TEAM_WORTH (t_Name, t_Value) values ('Island Senecio', 509582);
insert into TEAM_WORTH (t_Name, t_Value) values ('Yellow Meadowbeauty', 28979);
insert into TEAM_WORTH (t_Name, t_Value) values ('Mexican Bladdersage', 53166);
insert into TEAM_WORTH (t_Name, t_Value) values ('Virginia Quillwort', 900901);
insert into TEAM_WORTH (t_Name, t_Value) values ('Arborescent Pricklypear', 364518);
insert into TEAM_WORTH (t_Name, t_Value) values ('Spilanthes', 344794);
insert into TEAM_WORTH (t_Name, t_Value) values ('Brickellbush', 91596);
insert into TEAM_WORTH (t_Name, t_Value) values ('Lanszwert''s Pea', 639608);
insert into TEAM_WORTH (t_Name, t_Value) values ('Plantain Goldenweed', 350739);
insert into TEAM_WORTH (t_Name, t_Value) values ('Snow Mountain Beardtongue', 154855);
insert into TEAM_WORTH (t_Name, t_Value) values ('Old Man''s Whiskers', 252688);
insert into TEAM_WORTH (t_Name, t_Value) values ('Bachang', 982360);
insert into TEAM_WORTH (t_Name, t_Value) values ('Torrey''s Tievine', 221470);
insert into TEAM_WORTH (t_Name, t_Value) values ('Quebracho', 231954);
insert into TEAM_WORTH (t_Name, t_Value) values ('Unequal Leaf Bryoerythrophyllum Moss', 300202);
insert into TEAM_WORTH (t_Name, t_Value) values ('Whitemargin Phlox', 204018);
insert into TEAM_WORTH (t_Name, t_Value) values ('Chaenothecopsis Lichen', 763983);
insert into TEAM_WORTH (t_Name, t_Value) values ('Beach Suncup', 741539);
insert into TEAM_WORTH (t_Name, t_Value) values ('Smallflower Columbine', 845650);
insert into TEAM_WORTH (t_Name, t_Value) values ('Atlantic Goldenrod', 494600);
insert into TEAM_WORTH (t_Name, t_Value) values ('Carolina Leaf-flower', 224289);
insert into TEAM_WORTH (t_Name, t_Value) values ('Pohlia Moss', 290869);
insert into TEAM_WORTH (t_Name, t_Value) values ('Field Pennycress', 468308);
insert into TEAM_WORTH (t_Name, t_Value) values ('Byssoloma Lichen', 21621);
insert into TEAM_WORTH (t_Name, t_Value) values ('Sanddune Wallflower', 161510);
insert into TEAM_WORTH (t_Name, t_Value) values ('Prickly Russian Thistle', 825226);
insert into TEAM_WORTH (t_Name, t_Value) values ('Spiral Ginger', 746624);
insert into TEAM_WORTH (t_Name, t_Value) values ('Spiked Ipomopsis', 39965);
insert into TEAM_WORTH (t_Name, t_Value) values ('Koehler''s Rockcress', 880320);
insert into TEAM_WORTH (t_Name, t_Value) values ('Pale Bastard Toadflax', 150959);
insert into TEAM_WORTH (t_Name, t_Value) values ('Weak Spurge', 4224);
insert into TEAM_WORTH (t_Name, t_Value) values ('Gentian', 188254);
insert into TEAM_WORTH (t_Name, t_Value) values ('Canadian Licorice-root', 204760);
insert into TEAM_WORTH (t_Name, t_Value) values ('Dooryard Dock', 863162);
insert into TEAM_WORTH (t_Name, t_Value) values ('Zygodon Moss', 893005);
insert into TEAM_WORTH (t_Name, t_Value) values ('Catillaria Lichen', 724026);
insert into TEAM_WORTH (t_Name, t_Value) values ('Fivefingers', 735571);
insert into TEAM_WORTH (t_Name, t_Value) values ('Cusick''s Popcornflower', 310629);
insert into TEAM_WORTH (t_Name, t_Value) values ('Davis Mountain Oak', 332178);
insert into TEAM_WORTH (t_Name, t_Value) values ('Sessileleaf Bellwort', 129514);
insert into TEAM_WORTH (t_Name, t_Value) values ('Evans'' Felt Lichen', 11646);
insert into TEAM_WORTH (t_Name, t_Value) values ('Albizia', 364769);
insert into TEAM_WORTH (t_Name, t_Value) values ('Earth Lichen', 982379);
insert into TEAM_WORTH (t_Name, t_Value) values ('Chinese Fir', 919312);
insert into TEAM_WORTH (t_Name, t_Value) values ('Adobe Lily', 471094);
insert into TEAM_WORTH (t_Name, t_Value) values ('Broom Crowberry', 420220);
insert into TEAM_WORTH (t_Name, t_Value) values ('Bulblet-bearing Water Hemlock', 448364);
insert into TEAM_WORTH (t_Name, t_Value) values ('Gray''s Flatsedge', 198651);
insert into TEAM_WORTH (t_Name, t_Value) values ('Hoary Ticktrefoil', 984502);
insert into TEAM_WORTH (t_Name, t_Value) values ('Brant''s Oak', 534273);
insert into TEAM_WORTH (t_Name, t_Value) values ('Selkirk''s Violet', 796767);
insert into TEAM_WORTH (t_Name, t_Value) values ('Pine Violet', 576428);
insert into TEAM_WORTH (t_Name, t_Value) values ('Rim Lichen', 568160);
insert into TEAM_WORTH (t_Name, t_Value) values ('Orthotrichum Moss', 839537);
insert into TEAM_WORTH (t_Name, t_Value) values ('Gymnadenia', 382782);
insert into TEAM_WORTH (t_Name, t_Value) values ('Dense Blazing Star', 21336);
insert into TEAM_WORTH (t_Name, t_Value) values ('Plum Pine', 491550);
insert into TEAM_WORTH (t_Name, t_Value) values ('San Joaquin Dodder', 488553);
insert into TEAM_WORTH (t_Name, t_Value) values ('Forked Fanwort', 523764);
insert into TEAM_WORTH (t_Name, t_Value) values ('California Brome', 574900);
insert into TEAM_WORTH (t_Name, t_Value) values ('Dicranum Moss', 735160);
insert into TEAM_WORTH (t_Name, t_Value) values ('Rayless Sunflower', 814380);
insert into TEAM_WORTH (t_Name, t_Value) values ('Matted Lichen', 674973);
insert into TEAM_WORTH (t_Name, t_Value) values ('Queen''s-delight', 652683);
insert into TEAM_WORTH (t_Name, t_Value) values ('Subterranean Indian Breadroot', 872629);
insert into TEAM_WORTH (t_Name, t_Value) values ('Godfrey''s Thoroughwort', 266546);
insert into TEAM_WORTH (t_Name, t_Value) values ('Ragged Lichen', 812093);
insert into TEAM_WORTH (t_Name, t_Value) values ('Branching Phacelia', 372541);
insert into TEAM_WORTH (t_Name, t_Value) values ('Hopue', 910475);
insert into TEAM_WORTH (t_Name, t_Value) values ('Long-leaf Beak Sedge', 650835);
insert into TEAM_WORTH (t_Name, t_Value) values ('Parry''s Thistle', 276899);
insert into TEAM_WORTH (t_Name, t_Value) values ('Darlington''s Glade Spurge', 192905);
insert into TEAM_WORTH (t_Name, t_Value) values ('White Sage', 327256);
insert into TEAM_WORTH (t_Name, t_Value) values ('Dicranum Moss', 46317);
insert into TEAM_WORTH (t_Name, t_Value) values ('Oneawn Spineflower', 697784);
insert into TEAM_WORTH (t_Name, t_Value) values ('White Sagebrush', 194128);
insert into TEAM_WORTH (t_Name, t_Value) values ('Cypress Spurge', 718145);
insert into TEAM_WORTH (t_Name, t_Value) values ('Rush Pussytoes', 106267);
insert into TEAM_WORTH (t_Name, t_Value) values ('Vahl''s Cinquefoil', 830976);
insert into TEAM_WORTH (t_Name, t_Value) values ('Ropalospora Lichen', 324300);
insert into TEAM_WORTH (t_Name, t_Value) values ('Green Fiddleneck', 297511);
insert into TEAM_WORTH (t_Name, t_Value) values ('Parks'' Stoneseed', 409887);
insert into TEAM_WORTH (t_Name, t_Value) values ('Golden Dwarfgentian', 197536);
insert into TEAM_WORTH (t_Name, t_Value) values ('Sea Fig', 172524);
insert into TEAM_WORTH (t_Name, t_Value) values ('Marsh Bellflower', 693916);
insert into TEAM_WORTH (t_Name, t_Value) values ('Caribbean Bristlegrass', 932779);
insert into TEAM_WORTH (t_Name, t_Value) values ('Pseudolmedia', 875292);
insert into TEAM_WORTH (t_Name, t_Value) values ('Devilshead', 144923);
insert into TEAM_WORTH (t_Name, t_Value) values ('Starveling Milkvetch', 662099);
insert into TEAM_WORTH (t_Name, t_Value) values ('Narrowleaf Blue-eyed Grass', 293546);
insert into TEAM_WORTH (t_Name, t_Value) values ('Siberian Crab Apple', 26782);
insert into TEAM_WORTH (t_Name, t_Value) values ('Wild Coco', 651254);
insert into TEAM_WORTH (t_Name, t_Value) values ('Kaumahana', 78654);
insert into TEAM_WORTH (t_Name, t_Value) values ('Coville''s Serviceberry', 186960);
insert into TEAM_WORTH (t_Name, t_Value) values ('Cymbalaria', 620494);
insert into TEAM_WORTH (t_Name, t_Value) values ('Cleft Phlox', 329111);
insert into TEAM_WORTH (t_Name, t_Value) values ('Holboell''s Rockcress', 710622);
insert into TEAM_WORTH (t_Name, t_Value) values ('Blackish Locoweed', 219469);
insert into TEAM_WORTH (t_Name, t_Value) values ('West Indian Bluestem', 592987);
insert into TEAM_WORTH (t_Name, t_Value) values ('Hill''s Lupine', 498960);
insert into TEAM_WORTH (t_Name, t_Value) values ('Teosinte', 87733);
insert into TEAM_WORTH (t_Name, t_Value) values ('Andreaea Moss', 297424);
insert into TEAM_WORTH (t_Name, t_Value) values ('Japanese Jasmine', 655777);
insert into TEAM_WORTH (t_Name, t_Value) values ('Speargrass', 800148);
insert into TEAM_WORTH (t_Name, t_Value) values ('Bryum Moss', 181705);
insert into TEAM_WORTH (t_Name, t_Value) values ('Fall Tansyaster', 172485);
insert into TEAM_WORTH (t_Name, t_Value) values ('Western Inflated Sedge', 581240);
insert into TEAM_WORTH (t_Name, t_Value) values ('Kangaroo Grass', 588658);
insert into TEAM_WORTH (t_Name, t_Value) values ('Beaked Hawksbeard', 732295);
insert into TEAM_WORTH (t_Name, t_Value) values ('Pohaku Cyanea', 429711);
insert into TEAM_WORTH (t_Name, t_Value) values ('Rocoto', 563178);
insert into TEAM_WORTH (t_Name, t_Value) values ('Tiburon Indian Paintbrush', 275528);
insert into TEAM_WORTH (t_Name, t_Value) values ('Netted Shrubverbena', 906150);
insert into TEAM_WORTH (t_Name, t_Value) values ('Zeller''s Mock Orange', 539280);
insert into TEAM_WORTH (t_Name, t_Value) values ('Dwarf Phlox', 851596);
insert into TEAM_WORTH (t_Name, t_Value) values ('Schied''s Snakeherb', 312832);
insert into TEAM_WORTH (t_Name, t_Value) values ('Sulphur Lichen', 872163);
insert into TEAM_WORTH (t_Name, t_Value) values ('Yellow Carolina Milkvine', 992221);
insert into TEAM_WORTH (t_Name, t_Value) values ('Pilot Range Cinquefoil', 164927);
