SET IDENTITY_INSERT PLAYER_PROFILE ON
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (1, 'Natalie Butner', '2001-03-21', 'Zava', 210, 36, 'Langur, gray');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (2, 'Townie Dei', '2016-01-24', 'Skalith', 213, 225, 'Plains zebra');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (3, 'Ingelbert Plumm', '2002-04-08', 'Roodel', 96, 230, 'Bee-eater, nubian');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (4, 'Karola Gabbitis', '2002-01-12', 'Talane', 14, 85, 'Zorro, azara''s');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (5, 'Louise McClaren', '2016-06-04', 'Kayveo', 99, 69, 'Antechinus, brown');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (6, 'Nicky Sollars', '2009-12-28', 'Buzzshare', 90, 44, 'Bustard, denham''s');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (7, 'Ford Cleeves', '2017-11-06', 'Realmix', 65, 162, 'Leopard, indian');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (8, 'Rosalind Jerrans', '2000-08-02', 'Dabjam', 25, 220, 'Sarus crane');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (9, 'Abbi Ladel', '2006-03-05', 'Jazzy', 222, 203, 'North American porcupine');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (10, 'Jeffy Mather', '2004-01-22', 'Jabbersphere', 20, 3, 'Wallaby, euro');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (11, 'Hewitt De Cruze', '2015-09-17', 'Aimbu', 61, 204, 'Ovenbird');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (12, 'Zaccaria Cloney', '2004-03-17', 'Shufflebeat', 123, 240, 'Owl, australian masked');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (13, 'Prudy Cottier', '2000-06-03', 'Topicblab', 164, 140, 'Butterfly, canadian tiger swallowtail');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (14, 'Leona Oherlihy', '2017-09-18', 'Nlounge', 95, 169, 'Moorhen, purple');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (15, 'Puff Vaudrey', '2017-07-23', 'Shuffletag', 5, 33, 'Bennett''s wallaby');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (16, 'Corenda Chritchley', '2008-11-18', 'Eazzy', 244, 225, 'Vulture, king');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (17, 'Ilaire Kiddy', '2013-10-31', 'Gevee', 12, 130, 'Mudskipper (unidentified)');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (18, 'Worth De la Barre', '2009-03-16', 'Browseblab', 93, 178, 'Heron, giant');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (19, 'Niels Zorn', '2011-09-25', 'Oyoyo', 85, 242, 'Cockatoo, long-billed');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (20, 'Dorolice Eversfield', '2014-12-29', 'Aibox', 133, 155, 'Red meerkat');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (21, 'Shina Castelletti', '2004-02-12', 'Thoughtmix', 15, 126, 'Parrot, hawk-headed');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (22, 'Waylan Gidley', '2008-01-16', 'Zooveo', 96, 65, 'Masked booby');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (23, 'Vannie Quenell', '2009-04-17', 'Tavu', 250, 62, 'Tortoise, burmese brown mountain');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (24, 'Northrup McBayne', '2010-01-17', 'Twimbo', 117, 243, 'Yellow-brown sungazer');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (25, 'Aubry Welfare', '2013-08-09', 'Katz', 120, 65, 'Hyena, brown');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (26, 'Katie Melding', '2008-10-23', 'Edgeify', 53, 163, 'African black crake');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (27, 'Dori Acreman', '2000-06-12', 'Divavu', 74, 47, 'African lynx');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (28, 'Ellary Cornier', '2017-07-13', 'Photobug', 74, 188, 'Arctic hare');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (29, 'Katie Hughes', '2008-04-10', 'Browsebug', 207, 225, 'African fish eagle');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (30, 'Morganne Hulme', '2002-03-11', 'Aimbu', 131, 39, 'Starling, superb');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (31, 'Emeline Oswald', '2007-11-26', 'Avamba', 240, 122, 'Woodrat (unidentified)');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (32, 'Edsel Gaynesford', '2015-03-07', 'Riffpedia', 135, 26, 'Lemming, arctic');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (33, 'Emmott Bromfield', '2006-09-16', 'Quimba', 98, 122, 'Kudu, greater');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (34, 'Bond Eckert', '2012-07-14', 'Twitternation', 203, 222, 'Barrows goldeneye');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (35, 'Bernardine Russen', '2014-06-06', 'Shuffletag', 216, 9, 'Deer, spotted');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (36, 'Bondie Nekrews', '2009-03-16', 'Riffpath', 183, 28, 'Jaguarundi');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (37, 'Bentlee Sprosson', '2003-03-01', 'Realbuzz', 78, 29, 'Common wolf');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (38, 'Brooke Sudlow', '2001-05-29', 'Flashdog', 51, 103, 'Klipspringer');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (39, 'Hart Belloch', '2013-07-09', 'Yabox', 92, 126, 'Malachite kingfisher');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (40, 'Stanleigh Vaan', '2014-03-24', 'Skyndu', 107, 135, 'North American beaver');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (41, 'Jarrett Barfitt', '2015-08-09', 'Gigashots', 153, 25, 'Moorhen, purple');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (42, 'Lief Kock', '2012-06-28', 'Quire', 236, 97, 'Racer snake');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (43, 'Morgana Sydenham', '2017-08-03', 'Edgeclub', 117, 78, 'Eagle, tawny');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (44, 'Abe Whear', '2014-09-01', 'Pixonyx', 74, 98, 'Manatee');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (45, 'Domini Edworthy', '2000-12-12', 'Twinte', 158, 111, 'Heron, green');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (46, 'Darnall Gilli', '2006-01-15', 'Roodel', 146, 221, 'Legaan, water');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (47, 'Hurleigh Minnis', '2012-08-21', 'Oyonder', 215, 76, 'Squirrel, european red');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (48, 'Matilde Soan', '2004-04-25', 'Riffwire', 238, 12, 'Rufous-collared sparrow');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (49, 'Henka Castri', '2016-11-29', 'Tagtune', 120, 106, 'Asian water buffalo');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (50, 'Marcile Pimme', '2004-03-13', 'Tazz', 157, 32, 'Little cormorant');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (51, 'Pebrook Martyntsev', '2006-11-06', 'Twitternation', 241, 19, 'Flycatcher, tyrant');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (52, 'Amandi Grelik', '2006-01-16', 'Vimbo', 85, 247, 'Wild turkey');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (53, 'Cornelle Cestard', '2011-09-16', 'Bubbletube', 153, 5, 'Coqui partridge');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (54, 'Shae Delooze', '2008-11-17', 'Skyba', 210, 202, 'Striped dolphin');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (55, 'Tonya McNulty', '2009-11-02', 'Wordpedia', 178, 212, 'Spotted-tailed quoll');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (56, 'Way Crown', '2011-07-17', 'Tagfeed', 82, 245, 'Asiatic wild ass');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (57, 'Malvina Male', '2007-07-23', 'Thoughtbridge', 99, 201, 'Cockatoo, slender-billed');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (58, 'Brandyn Varsey', '2002-03-28', 'Janyx', 206, 190, 'Hawk-headed parrot');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (59, 'Daniele Brettel', '2014-08-12', 'Fadeo', 26, 166, 'White-rumped vulture');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (60, 'Dwayne Traite', '2006-12-19', 'Divape', 215, 86, 'Red-tailed cockatoo');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (61, 'Richy Thornebarrow', '2013-01-28', 'Twiyo', 152, 161, 'Arctic ground squirrel');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (62, 'Selestina Echelle', '2014-10-23', 'Devify', 67, 127, 'Asian false vampire bat');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (63, 'Delano Woollends', '2016-06-07', 'Realmix', 26, 17, 'Western bearded dragon');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (64, 'Ilsa Fullicks', '2009-04-12', 'Tagfeed', 240, 165, 'Snowy owl');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (65, 'Bordie Sydry', '2010-02-14', 'Eazzy', 153, 121, 'Grey-footed squirrel');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (66, 'Ahmad Antonovic', '2009-12-18', 'Browsecat', 133, 90, 'Genet, small-spotted');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (67, 'Norene Meritt', '2011-04-18', 'Twitterbridge', 195, 201, 'Dove, mourning collared');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (68, 'Halsy Pressey', '2004-05-12', 'Lazzy', 191, 11, 'Cockatoo, long-billed');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (69, 'Edwina Prall', '2016-10-20', 'Jabbercube', 24, 201, 'Woodpecker, downy');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (70, 'Florance Bonniface', '2009-01-20', 'Dabvine', 114, 174, 'Phalarope, northern');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (71, 'Ruthy Dibner', '2013-08-01', 'Realblab', 85, 93, 'Albatross, galapagos');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (72, 'Lawry Haggart', '2010-12-31', 'Babbleopia', 49, 5, 'Caracal');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (73, 'Georgette Jacklings', '2015-03-17', 'LiveZ', 27, 45, 'White-tailed jackrabbit');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (74, 'Geno Passion', '2017-11-07', 'Thoughtmix', 141, 165, 'Savanna fox');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (75, 'Creight Oxbury', '2008-02-11', 'Yakidoo', 164, 206, 'Squirrel, richardson''s ground');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (76, 'Rafferty Dulson', '2014-05-11', 'Skyba', 105, 185, 'Honey badger');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (77, 'Tessy Rushford', '2002-03-25', 'Flashspan', 141, 100, 'Yellow baboon');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (78, 'Lucky Aldwinckle', '2001-09-03', 'Minyx', 233, 77, 'European badger');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (79, 'Hattie Robertelli', '2017-07-04', 'Feedfire', 70, 85, 'Common wolf');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (80, 'Brigitte Methven', '2014-06-27', 'Fadeo', 113, 169, 'Trotter, lily');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (81, 'Ansley Cahn', '2001-04-06', 'Yadel', 81, 50, 'Tailless tenrec');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (82, 'Leoine Cowhig', '2013-12-17', 'Centidel', 215, 162, 'Otter, brazilian');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (83, 'Rachel Hundal', '2012-08-27', 'Topicblab', 222, 17, 'Great egret');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (84, 'Anna Nickell', '2009-07-22', 'Realmix', 23, 185, 'Javan gold-spotted mongoose');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (85, 'Antonia Aubry', '2016-11-25', 'Dazzlesphere', 145, 67, 'Mexican boa');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (86, 'Trish Killgus', '2016-10-20', 'Jabbersphere', 28, 161, 'Black-backed jackal');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (87, 'Mercedes Khosa', '2002-01-23', 'Twitterbeat', 51, 57, 'Cottonmouth');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (88, 'Ruy Chattell', '2004-04-19', 'Wordware', 213, 222, 'European wild cat');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (89, 'Bert Bedding', '2005-11-16', 'Brainlounge', 27, 130, 'Bandicoot, southern brown');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (90, 'Terrence Rechert', '2002-06-26', 'Browsezoom', 183, 154, 'Burmese black mountain tortoise');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (91, 'Delilah Land', '2005-04-15', 'Yodo', 41, 88, 'Galapagos penguin');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (92, 'Ned Drewe', '2017-08-11', 'Skinte', 192, 139, 'Laughing dove');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (93, 'Chen Courtes', '2015-06-08', 'Zoombeat', 180, 107, 'Asian openbill');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (94, 'Osbert Lawrie', '2009-10-15', 'Jetwire', 128, 168, 'Sockeye salmon');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (95, 'Tish Albone', '2017-07-17', 'Topicblab', 147, 162, 'Greater blue-eared starling');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (96, 'Devi Galiero', '2012-11-15', 'Aimbu', 220, 106, 'Columbian rainbow boa');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (97, 'Cherish Doak', '2003-12-18', 'Jabbertype', 23, 200, 'Chipmunk, least');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (98, 'Delcina Lampet', '2005-09-27', 'Flipstorm', 120, 113, 'Bison, american');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (99, 'Burch Shacklady', '2001-11-30', 'Livepath', 164, 161, 'Ovenbird');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (100, 'Sallyann Stratley', '2014-11-12', 'Browsetype', 96, 25, 'Heron, grey');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (101, 'Isiahi Hares', '2005-07-12', 'Midel', 133, 135, 'Bat, asian false vampire');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (102, 'Nial MacGoun', '2001-05-05', 'Cogilith', 145, 112, 'Currasow (unidentified)');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (103, 'Portie Redish', '2004-05-08', 'Aimbo', 59, 217, 'Curlew, black');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (104, 'Ciro Beckinsall', '2002-05-08', 'Twitterlist', 239, 98, 'Two-toed tree sloth');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (105, 'Simmonds Eldridge', '2010-06-16', 'Babbleopia', 236, 157, 'Lark, horned');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (106, 'Wit Pentycost', '2017-03-29', 'Brightdog', 20, 184, 'Fox, cape');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (107, 'Jeremias Phateplace', '2009-12-05', 'Geba', 43, 71, 'Bird, bare-faced go away');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (108, 'Magdaia Hake', '2004-11-02', 'Twitterwire', 123, 223, 'Long-tailed skua');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (109, 'Ky Sandison', '2009-04-07', 'Edgeclub', 102, 162, 'Beaver, eurasian');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (110, 'Norri Turone', '2010-11-24', 'Tagfeed', 158, 8, 'Wallaby, tammar');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (111, 'Angil Planks', '2003-10-19', 'Edgepulse', 213, 21, 'Macaw, blue and gold');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (112, 'Renard Lube', '2007-02-14', 'Voolia', 190, 68, 'Crane, sarus');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (113, 'Angie Perassi', '2006-12-19', 'Jabbertype', 61, 4, 'Bonnet macaque');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (114, 'Alberto Trundler', '2012-09-23', 'Buzzbean', 43, 145, 'Neotropic cormorant');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (115, 'Amalee Scandrite', '2009-12-03', 'Abata', 219, 215, 'Armadillo, giant');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (116, 'Deerdre Atwell', '2003-07-28', 'Tagpad', 117, 17, 'Dunnart, fat-tailed');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (117, 'Flora Piatek', '2006-06-18', 'Layo', 71, 226, 'Rainbow lory');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (118, 'Reinwald Seeds', '2000-01-19', 'Skinder', 5, 15, 'Eastern quoll');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (119, 'Helli Fomichkin', '2008-08-22', 'Skipstorm', 23, 194, 'Black and white colobus');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (120, 'Nomi Peppett', '1999-12-21', 'Jatri', 111, 8, 'Common raccoon');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (121, 'Dexter Dempsey', '2000-11-29', 'Skyndu', 105, 63, 'Great cormorant');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (122, 'Starlin Skittles', '2011-02-08', 'Photobug', 177, 83, 'Polecat, african');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (123, 'Brigg Siman', '2015-07-17', 'Photojam', 149, 217, 'Glider, sugar');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (124, 'Colline Hayer', '2004-09-08', 'Riffwire', 180, 248, 'Field flicker');
insert into PLAYER_PROFILE (PLAYER_ID, PNAME, DOB, COLLEGE, HEIGHT, WEIGHT, POSITION) values (125, 'Corella Basant', '2001-07-26', 'Thoughtstorm', 238, 17, 'Dragon, ornate rock');
