insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (1, 'Amazon', 'Technology');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (2, 'Microsoft', 'Technology');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (3, 'Oracle', 'Technology');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (4, 'Google', 'Technology');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (5, 'USPS', 'Transportation');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (6, 'UPS', 'Transportation');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (7, 'FedEx', 'Transportation');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (8, 'Chase', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (9, 'US Bank', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (10, 'Wells Fargo', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (11, 'Walmart', 'Retail');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (12, 'Target', 'Retail');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (13, 'Fred Meyer', 'Retail');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (14, 'Sears', 'Retail');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (15, 'Toyota', 'Car');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (16, 'Honda', 'Car');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (17, 'GM', 'Car');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (18, 'BMW', 'Car');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (19, 'Subaru', 'Car');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (20, 'Mazda', 'Car');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (21, 'Oodoo', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (22, 'Teklist', 'Consumer Non-Durables');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (23, 'Mita', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (24, 'Dabfeed', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (25, 'Jatri', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (26, 'Zava', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (27, 'Skipfire', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (28, 'Edgeblab', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (29, 'Viva', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (30, 'Leenti', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (31, 'Minyx', 'Public Utilities');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (32, 'Zoonoodle', 'Public Utilities');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (33, 'Zoomdog', 'Public Utilities');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (34, 'Abata', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (35, 'Photobug', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (36, 'Trunyx', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (37, 'Roombo', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (38, 'Youopia', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (39, 'InnoZ', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (40, 'Kanoodle', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (41, 'Tagchat', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (42, 'Demimbu', 'Public Utilities');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (43, 'Oozz', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (44, 'Brainsphere', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (45, 'Thoughtbeat', 'Technology');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (46, 'Tazz', 'Transportation');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (47, 'Brainlounge', 'Capital Goods');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (48, 'Vinte', 'Public Utilities');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (49, 'Oyonder', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (50, 'Jatri', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (51, 'Eayo', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (52, 'Avamba', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (53, 'Devpulse', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (54, 'Topicblab', 'Capital Goods');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (55, 'Dynabox', 'Consumer Durables');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (56, 'Youfeed', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (57, 'Twitternation', 'Transportation');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (58, 'Avaveo', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (59, 'Skimia', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (60, 'Meedoo', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (61, 'Wikivu', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (62, 'Aivee', 'Capital Goods');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (63, 'Wordtune', 'Capital Goods');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (64, 'Quire', 'Consumer Durables');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (65, 'Pixope', 'Capital Goods');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (66, 'Skibox', 'Technology');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (67, 'Brightdog', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (68, 'Skalith', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (69, 'Thoughtstorm', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (70, 'Photobug', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (71, 'Devpoint', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (72, 'Youbridge', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (73, 'Linklinks', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (74, 'Zoozzy', 'Consumer Non-Durables');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (75, 'Feednation', 'Technology');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (76, 'Abata', 'Capital Goods');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (77, 'Eare', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (78, 'Myworks', 'Technology');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (79, 'Devbug', 'Capital Goods');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (80, 'Izio', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (81, 'Vinte', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (82, 'Brainlounge', 'Capital Goods');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (83, 'Centizu', 'Energy');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (84, 'Skiba', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (85, 'Rhycero', 'Consumer Non-Durables');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (86, 'Lajo', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (87, 'Riffpath', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (88, 'Realcube', 'Consumer Non-Durables');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (89, 'Twinte', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (90, 'Jayo', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (91, 'Skinix', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (92, 'Feedspan', 'Transportation');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (93, 'Wikizz', 'Technology');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (94, 'Myworks', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (95, 'Mymm', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (96, 'Dynabox', 'Capital Goods');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (97, 'Zazio', 'Public Utilities');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (98, 'Yabox', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (99, 'Meezzy', 'Consumer Non-Durables');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (100, 'Aivee', 'Technology');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (101, 'Livefish', 'Retail');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (102, 'Skyba', 'Capital Goods');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (103, 'Ntags', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (104, 'Edgeify', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (105, 'Trilia', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (106, 'Blogtags', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (107, 'Brainsphere', 'Public Utilities');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (108, 'Ooba', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (109, 'Yakidoo', 'Transportation');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (110, 'Teklist', 'Finance');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (111, 'Flipstorm', 'Basic Industries');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (112, 'Skipfire', 'Public Utilities');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (113, 'Vipe', 'Technology');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (114, 'Skinder', 'Public Utilities');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (115, 'Pixope', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (116, 'Riffpedia', 'Capital Goods');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (117, 'Skajo', 'Capital Goods');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (118, 'Edgepulse', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (119, 'Trunyx', 'Public Utilities');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (120, 'Twiyo', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (121, 'Myworks', 'Health Care');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (122, 'Skivee', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (123, 'Jabbertype', 'Consumer Services');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (124, 'Meezzy', 'Retail');
insert into SPONSOR (sponsorId, sponsorName, sponsorBusiness) values (125, 'Edgeify', 'Consumer Services');
