insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (43, 'Tolmie''s Owl''s-clover', 1, 4, 0.83, 0.87);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (137, 'Dotted Wild Coffee', 2, 1, 0.97, 0.49);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (94, 'Slender False Garlic', 3, 5, 0.46, 0.46);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (143, 'Tarweed', 4, 6, 0.3, 0.19);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (90, 'Longleaf Primrose-willow', 5, 6, 0.73, 0.57);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (140, 'Showy Phlox', 6, 1, 0.16, 1.0);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (158, 'Island Senecio', 7, 4, 1.0, 0.91);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (131, 'Yellow Meadowbeauty', 8, 3, 0.88, 0.7);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (120, 'Mexican Bladdersage', 9, 6, 0.9, 0.77);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (46, 'Virginia Quillwort', 10, 1, 0.85, 0.61);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (121, 'Arborescent Pricklypear', 11, 4, 0.92, 0.72);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (67, 'Spilanthes', 12, 3, 0.81, 0.27);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (3, 'Brickellbush', 13, 6, 0.68, 0.45);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (121, 'Lanszwert''s Pea', 14, 6, 0.82, 0.52);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (66, 'Plantain Goldenweed', 15, 3, 0.52, 0.3);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (60, 'Snow Mountain Beardtongue', 16, 1, 0.98, 0.35);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (126, 'Old Man''s Whiskers', 17, 3, 0.59, 0.71);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (82, 'Bachang', 18, 5, 0.98, 0.72);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (63, 'Torrey''s Tievine', 19, 3, 0.22, 0.04);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (65, 'Quebracho', 20, 6, 0.55, 0.82);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (98, 'Unequal Leaf Bryoerythrophyllum Moss', 21, 2, 0.51, 0.72);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (167, 'Whitemargin Phlox', 22, 3, 0.93, 0.84);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (4, 'Chaenothecopsis Lichen', 23, 2, 0.63, 0.87);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (149, 'Beach Suncup', 24, 6, 0.95, 0.28);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (172, 'Smallflower Columbine', 25, 1, 0.71, 0.78);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (135, 'Atlantic Goldenrod', 26, 3, 0.19, 0.11);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (166, 'Carolina Leaf-flower', 27, 6, 0.79, 0.94);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (88, 'Pohlia Moss', 28, 4, 0.65, 0.55);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (27, 'Field Pennycress', 29, 6, 0.26, 0.86);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (105, 'Byssoloma Lichen', 30, 6, 0.14, 0.9);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (184, 'Sanddune Wallflower', 31, 5, 0.12, 0.38);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (171, 'Prickly Russian Thistle', 32, 4, 0.43, 0.47);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (134, 'Spiral Ginger', 33, 1, 0.97, 0.06);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (177, 'Spiked Ipomopsis', 34, 5, 0.69, 0.65);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (88, 'Koehler''s Rockcress', 35, 5, 0.14, 0.72);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (110, 'Pale Bastard Toadflax', 36, 4, 0.76, 0.06);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (189, 'Weak Spurge', 37, 6, 0.97, 0.62);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (62, 'Gentian', 38, 4, 0.56, 0.08);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (184, 'Canadian Licorice-root', 39, 6, 0.75, 0.56);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (155, 'Dooryard Dock', 40, 4, 0.07, 0.66);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (139, 'Zygodon Moss', 41, 1, 0.02, 0.25);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (91, 'Catillaria Lichen', 42, 6, 0.01, 0.83);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (10, 'Fivefingers', 43, 1, 0.21, 0.03);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (85, 'Cusick''s Popcornflower', 44, 4, 0.1, 0.25);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (104, 'Davis Mountain Oak', 45, 3, 0.55, 0.21);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (170, 'Sessileleaf Bellwort', 46, 5, 0.4, 0.61);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (70, 'Evans'' Felt Lichen', 47, 2, 0.81, 0.68);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (196, 'Albizia', 48, 1, 0.14, 0.68);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (128, 'Earth Lichen', 49, 2, 0.37, 0.53);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (163, 'Chinese Fir', 50, 3, 0.29, 0.66);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (174, 'Adobe Lily', 51, 1, 0.89, 0.68);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (79, 'Broom Crowberry', 52, 6, 0.79, 0.57);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (139, 'Bulblet-bearing Water Hemlock', 53, 6, 1.0, 0.44);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (33, 'Gray''s Flatsedge', 54, 1, 0.89, 0.48);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (9, 'Hoary Ticktrefoil', 55, 2, 0.44, 0.03);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (102, 'Brant''s Oak', 56, 5, 0.33, 0.37);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (191, 'Selkirk''s Violet', 57, 5, 0.17, 0.73);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (139, 'Pine Violet', 58, 1, 0.73, 0.63);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (143, 'Rim Lichen', 59, 4, 0.45, 0.54);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (129, 'Orthotrichum Moss', 60, 2, 0.86, 0.14);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (42, 'Gymnadenia', 61, 1, 0.69, 0.36);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (109, 'Dense Blazing Star', 62, 5, 0.99, 0.66);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (186, 'Plum Pine', 63, 3, 0.97, 0.75);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (136, 'San Joaquin Dodder', 64, 5, 0.13, 0.79);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (19, 'Forked Fanwort', 65, 1, 0.42, 0.95);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (151, 'California Brome', 66, 2, 0.27, 0.63);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (32, 'Dicranum Moss', 67, 5, 0.72, 0.77);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (133, 'Rayless Sunflower', 68, 3, 0.51, 0.98);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (199, 'Matted Lichen', 69, 5, 0.26, 0.01);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (120, 'Queen''s-delight', 70, 5, 0.71, 0.41);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (52, 'Subterranean Indian Breadroot', 71, 2, 0.21, 0.35);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (155, 'Godfrey''s Thoroughwort', 72, 6, 0.83, 0.4);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (97, 'Ragged Lichen', 73, 2, 0.19, 0.04);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (31, 'Branching Phacelia', 74, 4, 0.96, 0.22);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (174, 'Hopue', 75, 5, 0.52, 0.42);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (162, 'Long-leaf Beak Sedge', 76, 2, 0.62, 0.78);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (3, 'Parry''s Thistle', 77, 2, 0.1, 0.56);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (151, 'Darlington''s Glade Spurge', 78, 4, 0.72, 1.0);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (86, 'White Sage', 79, 1, 0.98, 0.57);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (168, 'Dicranum Moss', 80, 2, 0.04, 0.59);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (189, 'Oneawn Spineflower', 81, 4, 0.9, 0.57);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (21, 'White Sagebrush', 82, 1, 0.98, 0.77);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (109, 'Cypress Spurge', 83, 3, 0.81, 0.11);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (192, 'Rush Pussytoes', 84, 3, 0.69, 0.39);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (119, 'Vahl''s Cinquefoil', 85, 3, 0.71, 0.86);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (20, 'Ropalospora Lichen', 86, 4, 0.68, 0.57);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (169, 'Green Fiddleneck', 87, 2, 0.29, 0.5);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (188, 'Parks'' Stoneseed', 88, 2, 0.05, 0.81);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (24, 'Golden Dwarfgentian', 89, 3, 0.56, 0.08);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (68, 'Sea Fig', 90, 6, 0.67, 0.79);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (2, 'Marsh Bellflower', 91, 6, 0.84, 0.23);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (20, 'Caribbean Bristlegrass', 92, 6, 0.25, 0.56);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (56, 'Pseudolmedia', 93, 3, 0.38, 0.75);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (132, 'Devilshead', 94, 6, 0.55, 0.02);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (114, 'Starveling Milkvetch', 95, 3, 0.9, 0.22);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (22, 'Narrowleaf Blue-eyed Grass', 96, 3, 0.74, 0.61);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (8, 'Siberian Crab Apple', 97, 5, 0.4, 0.75);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (196, 'Wild Coco', 98, 5, 0.15, 0.71);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (77, 'Kaumahana', 99, 1, 0.11, 0.13);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (142, 'Coville''s Serviceberry', 100, 3, 0.96, 0.25);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (146, 'Cymbalaria', 101, 4, 0.15, 0.41);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (29, 'Cleft Phlox', 102, 3, 0.12, 0.38);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (167, 'Holboell''s Rockcress', 103, 3, 0.32, 0.96);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (140, 'Blackish Locoweed', 104, 2, 0.32, 0.46);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (168, 'West Indian Bluestem', 105, 3, 0.55, 0.89);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (44, 'Hill''s Lupine', 106, 1, 0.91, 0.71);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (145, 'Teosinte', 107, 4, 0.07, 0.22);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (199, 'Andreaea Moss', 108, 3, 0.15, 0.12);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (27, 'Japanese Jasmine', 109, 2, 0.7, 0.96);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (199, 'Speargrass', 110, 2, 0.91, 0.71);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (37, 'Bryum Moss', 111, 2, 0.42, 0.19);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (5, 'Fall Tansyaster', 112, 6, 0.52, 0.96);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (36, 'Western Inflated Sedge', 113, 6, 0.03, 0.03);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (171, 'Kangaroo Grass', 114, 4, 0.79, 0.84);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (38, 'Beaked Hawksbeard', 115, 6, 0.89, 0.45);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (35, 'Pohaku Cyanea', 116, 3, 0.88, 0.3);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (78, 'Rocoto', 117, 5, 0.67, 0.69);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (139, 'Tiburon Indian Paintbrush', 118, 3, 0.71, 0.04);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (130, 'Netted Shrubverbena', 119, 4, 0.66, 0.4);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (5, 'Zeller''s Mock Orange', 120, 4, 0.76, 0.08);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (23, 'Dwarf Phlox', 121, 1, 0.48, 0.44);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (137, 'Schied''s Snakeherb', 122, 5, 0.47, 0.49);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (189, 'Sulphur Lichen', 123, 1, 0.3, 0.54);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (141, 'Yellow Carolina Milkvine', 124, 4, 0.26, 0.31);
insert into TEAM (champWins, team_Name, t_City, d_Id, away_Percent, home_Percent) values (197, 'Pilot Range Cinquefoil', 125, 1, 0.65, 0.49);
